version: "3.3"

services:
    vue:
        build: ./vue
        ports:
            - "8080:8080"
        environment:
          #- PORT=3002
          - NODE_ENV=development
        volumes:
            - ../app:/var/www/app